name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: unit-ci
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
      - name: Install Dependencies
        run: |
          bundle install
      - name: Rake
        run: bundle exec rake
      - name: Run tests
        env:
          USER_TOKEN: ${{ secrets.UNIT_TOKEN }}
        run: rspec